services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ku_sheet_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: mysql://app:app@db:3306/ku_sheet_db
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5000"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
  uploads_data:


